[package]
name = "ArbitrageDashboard"
version = "1.0.0"
authors = []

[addresses]
arbitrage = "0x851c087b280c6853667631d72147716d15276a7383608257ca9736eb01cd6af9"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "mainnet" }
